//TODO GET SINGLE PRODUCT INCLUDING REVIEWS AND RANDOM PRODUCTS FROM THE SAME CATEGORY AND FROM SAME TAGS
//TODO ADD A REVIEW
//TODO ADD TO CART
//TODO REMOVE FROM CART

//TODO ADD TO ORDER
//TODO CANCEL AN ORDER

//TODO CHECK ORDERS STATUS

