//TODO REMOVE A PRODUCT 
//TODO ADD A PRODUCT WITH CERTAIN TAG AND A CATEGORY
//TODO ADD A CATEGORY
//TODO ADD A TAG
//WITH THAT TRANSACTION METHOD
//TODO REMOVE A PRODUCT
//TODO REMOVE A CATEGORY
//TODO REMOVE A TAG